package.json
src/components/TokenTable/TokenTable.stories.tsx
src/components/TokenTable/index.tsx

changes for https://github.com/HyperPlay-Gaming/hyperplay-store/pull/151
medium was too large for the button size for 500px width. leaving no spacing between token type and the button
updated the token display names

[UI] update ui for token table

---

package.json
src/common/types.ts
src/components/QuestLog/QuestLog.stories.tsx
src/components/QuestLog/index.module.scss
src/components/QuestLog/index.tsx

- fix the reputation type prop
- don't show headers for each section when there is only one section to show
- add story for the above

[Fix] Quest log styling improvements

---

package.json
yarn.lock

pulls in https://github.com/HyperPlay-Gaming/utils/pull/21

[Fix] upgrade hp utils

---

package.json
src/components/QuestCard/QuestCard.stories.tsx
src/components/QuestCard/index.module.scss
src/components/QuestCard/index.tsx

https://hyperplay-mszab4kkh-hyperplay.vercel.app/?path=/story/quests-questcard--without-game-title-and-descriptipn
This PR had to be urgent as had discussion with @iamdavid0091 about this

[feat]: Add rewardImage prop

---

package.json
src/components/QuestDetails/QuestDetails.stories.tsx
src/components/QuestDetails/QuestDetailsStory.module.scss
src/components/QuestDetails/index.module.scss
src/components/QuestDetails/index.tsx
src/components/QuestDetails/types.ts
yarn.lock

Paths: 
`/?path=/story/quests-questdetails--custom-cta-reputational-airdrop` and 
`/?path=/story/quests-questdetails--custom-cta-platstreak`

[feat]: Modify `QuestDetails` with latest design

---

package.json
src/components/QuestDetails/index.tsx
yarn.lock

throws document is undefined in hp store
we need this to be a separate component too

[Fix] rm markdown from details

---

package.json
src/components/QuestsSummaryTable/QuestsSummaryTable.stories.tsx
src/components/QuestsSummaryTable/index.module.scss
src/components/QuestsSummaryTable/index.tsx
src/components/SearchBar/SearchBar.module.scss
src/components/SearchBar/index.tsx

- add search bar to the quest summary table
- updated styling for search bar to figs some UI/UX issues
https://www.figma.com/design/GKPELZxk551oVC3EDLgEDA/Current-Design?node-id=11127-18768&m=dev

[Feat] add search bar to summary table

---

package.json
src/components/SearchBar/index.tsx

The input needs to be set if the search text prop changes

[Fix] Re-render search bar on prop searchText change

---

package.json
src/components/QuestDetails/QuestDetails.stories.tsx
src/components/QuestDetails/components/Reward/index.tsx

http://localhost:6006/?path=/story/quests-questdetails--reward-marketplace-link for the test

[fix]: Fixed view reward will only show if there is marketplace link available

---

package.json
src/components/QuestsSummaryTable/index.tsx

Generally just need these to be declarative for scroll event to scroll on specific div

[feat]: Add id, on scroll event for quests list

---

package.json
src/components/AccountAvatar/index.tsx
src/components/AccountAvatar/styles.module.scss

right now the offline avatar is 40x40 but the online avatar is 45x45

fix(avatar): make online and offline mode same size

---

package.json
src/components/QuestDetails/QuestDetails.stories.tsx
src/components/QuestDetails/components/StreakProgress/StreakProgress.stories.tsx
src/components/QuestDetails/components/StreakProgress/index.tsx
src/components/QuestDetails/types.ts

Add flag to show the external sync button. Disable it by default.

[Tech] Add flag for external sync button

---

.github/workflows/storybook-tests.yml
package.json
src/components/NavBarOverlay/NavBarOverlay.stories.tsx
src/components/NavItem/NavItem.module.scss
src/components/NavItem/index.tsx

adding coming soon prop to overlay nav bar item

[UI] Add coming soon label option to overlay nav bar item

---

package.json
src/components/GameCard/GameCard.stories.tsx
src/components/GameCard/components/DownloadBar/index.tsx
src/components/GameCard/index.tsx
src/components/GameCard/types.d.ts

Add Patching Statuses and actions.
Also removed the Pause button for the extracting method.

[UI] GameCard Patching Support

---

package.json
src/components/NavBarOverlay/NavBarOverlay.module.scss
src/components/NavBarOverlay/NavBarOverlay.stories.tsx
src/components/NavItem/NavItem.module.scss
src/components/NavItem/SubLink/SubLink.module.scss
src/components/NavItem/SubLink/index.tsx
src/components/NavItem/index.tsx
src/index.ts

Nav bar sublinks with collapsible parent NavItem
prereq for https://github.com/HyperPlay-Gaming/product-management/issues/667
design here: https://www.figma.com/design/GKPELZxk551oVC3EDLgEDA/Overlay?node-id=16873-11201&t=oWG3rn8hFBa6Hkwg-4
try it out here https://hyperplay-ui-git-ui-addnavbarsublink-hyperplay.vercel.app/?path=/docs/overlay-navbaroverlay--docs

[UI] add navbar sublinks

---

.gitignore2
package.json
src/components/NavBar/index.tsx

closes https://github.com/HyperPlay-Gaming/product-management/issues/646

submit-game => install HyperPlay

---

package.json

needed for https://github.com/HyperPlay-Gaming/product-management/issues/791

[Fix] types export

---

package.json
src/components/QuestsSummaryTable/QuestsSummaryTable.stories.tsx
src/components/QuestsSummaryTable/index.tsx

Rm sort dropdown by default. Use `searchBar` as the layout component prop

[UI] Remove sort from quests summary table

---

package.json
src/components/Carousel/Carousel.stories.tsx
src/components/Carousel/index.module.scss
src/components/Carousel/index.tsx

closes https://github.com/HyperPlay-Gaming/px-pm/issues/99

[UI] rm carousel gradient

---

package.json
src/components/NavBar/NavBar.module.scss
src/components/NavBar/NavBar.stories.tsx
src/components/NavBar/NavBarLink/index.module.scss
src/components/NavBar/NavBarLink/index.tsx
src/components/NavBar/index.tsx
src/index.ts

This brings in the best changes from the website navbar and makes the component general and reusable. Fixing many UI issues with the previous component.
For instance, changes to the items in the navbar do not require a hp-ui pr.
Now we support `next/link` as a prop for any link as well. by default it is still an `<a/>` tag
This pull request includes several updates to the `NavBar` component and its associated styles, as well as a version bump in the `package.json`. The most important changes include the refactoring of the `NavBar` component to support new props, the addition of a `NavBarLink` component, and the reorganization of styles.
* [`src/components/NavBar/index.tsx`](diffhunk://#diff-2ed8b1f20516c5ab6c29deda878453459f05a8756b231a9399bbfe5f4c553dbcL3-L79): Refactored the `NavBar` …

[Tech] Refactor navbar

---

package.json
src/components/Footer/index.tsx

[UI] add cookie policy link to Footer component

---

.github/workflows/check-version-bump.yml
package.json

[CI] Fix version bump check in workflow

---

package.json
src/components/SearchBar/SearchBar.stories.tsx
src/components/SearchBar/SearchBarStories.module.scss
src/components/SearchBar/index.tsx

- Add `renderItem` prop to allow custom rendering of suggestions.
- Introduce `dropdownList` style property for better styling control.
- Update stories to demonstrate new rendering capabilities with images and names.

[Feat] Enhance SearchBar with customizable item rendering and styles

---

package.json
src/components/MetaSection/MetaSection.module.scss

Updating from 12px to 8px to match figma

[UI] Update meta section gap

---

package.json
src/components/AssociatedGamesCollapse/index.module.scss
src/components/QuestDetails/components/Rewards/index.module.scss
src/components/QuestDetails/index.module.scss

figma link: https://www.figma.com/design/yHrBPoE70k1I2icW4paEit/Quests?node-id=1356-85942&t=udThrHzQBnNXxZZo-0

feat(quest-detail): increase border width

---

package.json
src/components/BlockchainsStack/index.tsx
src/components/GameInfoV2/GameInfoV2.module.scss
src/components/GameRequirementsTable/GameRequirementsTable.module.scss
src/components/GameRequirementsTable/GameRequirementsTable.stories.tsx
src/components/GameRequirementsTable/index.tsx
src/components/PlatformsSupported/index.tsx
src/components/RewardsSection/index.tsx
src/components/TokenTable/TokenTable.module.scss
src/components/TokenTable/TokenTable.stories.tsx
src/styles/designSystem/_typography.scss

related to https://github.com/HyperPlay-Gaming/px-pm/issues/295
- rm platforms supported playable on gradient
- fix breakpoint for game info v2
- fix game requirements table value overflows
- fix token table mobile breakpoint
- show blockchain icons on touch
- fix `title` type
- fix rewards section title type
This pull request includes various updates to the styling and structure of components in the codebase. The changes mainly focus on enhancing the responsiveness of styles, updating component structures, and refining the design system.
* [`src/components/GameInfoV2/GameInfoV2.module.scss`](diffhunk://#diff-03f99b1cec41455bc12a4ea6bda1bcdf2a386ca1db2549ee5f81014548119a96R2): Updated media query breakpoints to use `$tabletLandscapeBreakpoint` instead of hardcoded values. Added a new …

[UI] Updates for game details components

---

package.json
src/components/CardGeneric/index.tsx
src/components/PlatformsSupported/index.module.scss
src/components/RewardsCard/RewardsCard.stories.tsx
src/components/RewardsCard/index.module.scss
src/components/RewardsCard/index.tsx
src/components/RewardsSection/RewardsSection.module.scss
src/components/RewardsSection/RewardsSection.stories.tsx
src/components/RewardsSection/constants.ts
src/components/RewardsSection/index.tsx

Fix stylings after Design Review.
Store PR: https://github.com/HyperPlay-Gaming/hyperplay-store/pull/319

[FIx] Reward Card and Sections

---

package.json
src/components/CardGeneric/index.tsx
src/components/PlatformsSupported/index.module.scss
src/components/RewardsCard/RewardsCard.stories.tsx
src/components/RewardsCard/index.module.scss
src/components/RewardsCard/index.tsx
src/components/RewardsSection/RewardsSection.module.scss
src/components/RewardsSection/RewardsSection.stories.tsx
src/components/RewardsSection/constants.ts
src/components/RewardsSection/index.tsx

Reverts HyperPlay-Gaming/hyperplay-ui#486
reverting due to conflicts dependency with previous pr

Revert "[FIx] Reward Card and Sections"

---

package.json
src/components/QuestDetails/components/Reward/Reward.stories.tsx
src/components/QuestDetails/components/Reward/index.module.scss
src/components/QuestDetails/components/Reward/index.tsx

https://hyperplay-ui-git-feat-quest-reward-disable-hyperplay.vercel.app/?path=/docs/quests-questdetails-reward--docs#claim-not-available

feat(reward): add tooltip for claim button when reward is not available

---

src/components/QuestCard/index.module.scss
src/components/QuestCard/index.tsx

add tooltip on text overflow for reward name and quest description

[UI] Add tooltip

---

package.json
pnpm-lock.yaml
src/components/QuestsBanner/QuestsBanner.stories.tsx
src/components/QuestsBanner/index.tsx

Quests banner was throwing if only 1 item in banner.

[Fix] Quests banner for 1 banner item

---

package.json
src/components/QuestsBanner/index.tsx

- support generic button container
- do not show line when only 1 slide

[Fix] Misc quests banner fixes

---

package.json
src/components/DownloadToast/index.module.scss
src/components/DownloadToast/index.tsx

Closes: https://github.com/orgs/HyperPlay-Gaming/projects/16/views/8?pane=issue&itemId=114464159&issue=HyperPlay-Gaming%7Chyperplay-pm%7C597
I also refactored the toast styles after this conversation with @iamdavid0091 and @pimentel08:

Fix/ close button of the download toast

---

package.json

Small pr to update package Json

Update package version to 1.30.3

---

package.json
src/components/MasonryLayout/MasonryLayout.module.scss
src/components/MasonryLayout/MasonryLayout.stories.tsx
src/components/MasonryLayout/index.tsx
src/index.ts

Closes: https://github.com/orgs/HyperPlay-Gaming/projects/16/views/8?pane=issue&itemId=100172865&issue=HyperPlay-Gaming%7Chyperplay-pm%7C106

Feat/implement masonry layout component for New games section

---

package.json
src/components/HorizontalCard/HorizontalCard.module.scss

Fix children button hover when wrapped with an `a` tag. Also, set the same style for the `a` tag children so that when we make `Button` polymorphic, this won't break when it's an `a` tag root component

[UI] Update horizontal button selector

---

package.json
src/components/MasonryLayout/MasonryLayout.module.scss

closes: https://github.com/HyperPlay-Gaming/hyperplay-pm/issues/720

Fix/ match all gaps between cards on the New Games section 

---

package.json
src/components/HorizontalCard/HorizontalCard.stories.tsx
src/components/HorizontalCard/HorizontalCard.tsx
src/index.ts

Closes: https://github.com/orgs/HyperPlay-Gaming/projects/16/views/8?pane=issue&itemId=3290439877&issue=HyperPlay-Gaming%7Chyperplay-pm%7C750

Refactor HorizontalCard component to support custom class

---

package.json
src/components/Checkbox/Checkbox.module.scss
src/components/CheckboxList/CheckboxList.module.scss
src/components/Dropdowns/GenericDropdown/GenericDropdown.module.scss
src/components/Dropdowns/GenericDropdown/index.tsx
src/components/Dropdowns/OptionsDropdown/OptionsDropdown.module.scss
src/components/Dropdowns/OptionsDropdown/index.tsx
src/components/SearchBar/SearchBar.module.scss
src/components/SearchBar/SearchBar.stories.tsx
src/components/SearchBar/index.tsx
src/components/Toggle/Toggle.module.scss
src/components/Toggle/Toggle.stories.tsx

General ui changes to match the new design as closely as possible, although we use Mantine buttons for the dropdown, which makes styling like hover and selected a little difficult to change.
Will be used to close: https://github.com/orgs/HyperPlay-Gaming/projects/16/views/8?filterQuery=filter&pane=issue&itemId=102396920&issue=HyperPlay-Gaming%7Chyperplay-pm%7C188

UI/update filter UI
