HyperPlay-Gaming/hyperplay-ui

package.json
src/components/QuestDetails/QuestDetails.stories.tsx
src/components/QuestDetails/components/StreakProgress/StreakProgress.stories.tsx
src/components/QuestDetails/components/StreakProgress/index.tsx
src/components/QuestDetails/types.ts

- While the user is playing, percentage should update as they play the game
- Lightning bolt should be green at >= 100% completion for the day

[Quests] Make percent dynamic in quest details

---

package.json
src/components/Collapse/Collapse.module.scss
src/components/Collapse/index.tsx

Currently the button doesn't have any padding, the container does and as a result clicking the padding in the container doesn't trigger the collapse action.
By moving the padding to the button we can achieve making the padding space clickable.
Story: https://hyperplay-ui-git-fix-collapse-clickable-area-hyperplay.vercel.app/?path=/docs/collapse--docs

fix(collapse): make whole content clickable

---

package.json
src/components/SearchBar/index.tsx

The search memo prevents searching for a field that isn't the same field as in the suggestions dropdown
For instance, we are searching for game title and quest title matches on the quest summary page. This will show as no results for the game title suggestions in the popover.
Ultimately this is just too opinionated for a stateless ui library component
An on click handler is not needed on the svg either and throws a eslint error, so I removed it.

[Fix] rm search memo

---

package.json
src/components/AchievementCard/index.tsx
src/components/QuestCard/QuestCard.stories.tsx
src/components/QuestCard/index.tsx

This is required as we will pass the `id` for scroll to specific quest on quests list page

[feat]: Allow QuestCard to accept div attributes

---

package.json
src/components/QuestsSummaryTable/QuestsSummaryTable.stories.tsx
src/components/QuestsSummaryTable/index.module.scss
src/components/QuestsSummaryTable/index.tsx
src/components/SearchBar/index.tsx

Decouple search bar from summary table.
Needed so that I can set `withinPortal` on the search bar for the store page scrolling, which is only needed on the store page.

[Tech] decouple search bar from quests summary table

---

package.json
src/components/QuestDetails/components/Reward/index.module.scss
src/components/QuestDetails/components/Reward/index.tsx

The claims left text has always been there but we were placing it inside of the reward image which has `overflow: hidden`. Wrapping the components with a flex container solves the issue.
Preview: https://hyperplay-ui-git-fix-claims-left-hyperplay.vercel.app/?path=/story/quests-questdetails--play-streak

fix(quest-details): show num claims left

---

.github/workflows/storybook-tests.yml

Needed to downgrade the ubuntu runner since some of the playwright dependencies are not available on the latest version of ubuntu.
This doesn't affect anything though sine the headless browsers are the same on both ubuntu versions.

[Fix] Storybook tests

---

src/components/Sticker/index.module.scss
src/components/Sticker/index.tsx

This pr is to add the neutral, tertiary, and error badge colors, besides the filledStrong variant, which matches the DS and is needed in some other new components. 
DS: 
Storybook:

[UI] Add new badge colors

---

package.json
src/components/QuestDetails/QuestDetails.stories.tsx
src/components/QuestDetails/index.module.scss
src/components/QuestDetails/index.tsx
src/components/QuestDetails/types.ts

This PR adds the component on Storybook, I need this approved for use in the Client repository.
- Click on the  Storybook review link and search for the "QuestDetails" component

[Feature] Add game name to quest details component 

---

src/components/GameInfo/GameInfo.module.scss

This pr is a simple fix to center align the platform icons on the GameInfo component showed in the Game Details Page.

[fix]: Fix platform icons on GameInfo component

---

package.json
src/components/Carousel/Carousel.stories.tsx
src/components/Carousel/index.tsx

This pr removes the Game Title from the carousel in the Storybook, the next step is to update it in the client.

[UI] Remove title rendering and make title optional

---

package.json
src/components/StreakProgress/StreakProgress.stories.tsx
src/components/StreakProgress/index.tsx

add `streakIsProgressing` prop to enable the % completion interpolation which was on by default previously

[Fix] Streak progress when not playing

---

src/components/GameAbout/GameAbout.module.scss
src/components/GameAbout/GameAbout.stories.tsx
src/components/GameAbout/index.tsx

This PR is the first step to adding the game title to a location other than the carousel, as requested by @jacobc-eth. The game title was previously removed from the carousel component as asked, resulting in no game name on the game details page. Based on feedback from @pimentel08, we decided to put the game title in the About section, as it will be the future side place for that info.

[feat] Add game name to game page

---

package.json
src/components/LanguageSelector/LanguageSelector.stories.tsx
src/components/LanguageSelector/constants.ts
src/components/LanguageSelector/index.tsx

Right now if we want to use the selector, we need to show all the locale options. 
These changes support passing which are the locales we want to show as options.

feat(LanguageSelector): add support for choosing locales options

---

.github/workflows/check-version-bump.yml

Adds a new workflow that will warn if the version in package.json was not changed on the PR since this happens to us from time to time and we then need another commit to change it.

[CI] Add workflow to check for version bump in package.json

---

.github/workflows/storybook-tests.yml

our test GHA is using a runner that is already in a brown out and will be fully removed in a couple weeks
https://github.com/actions/runner-images/issues/11101

[Tech] use ubuntu latest for pw test gha 

---

package.json
src/styles/designSystem/_colors.scss

primary button gradient color broke on color var update. it was showing with no background color.
https://hyperplay-ui-git-feat-add-and-update-new-colors-hyperplay.vercel.app/?path=/story/button--large-primary
This reverts the color gradient 01 back to the original

[Fix] primary button gradient

---

package.json
src/components/Sticker/index.module.scss
src/components/Sticker/index.tsx
src/styles/designSystem/_colors.scss

Update filledStrong colors and borders on `Sticker` component to match `filled` in figma but not break existing `filled` variants using `Sticker`

[Chore] Update Sticker filledStrong colors

---

src/components/BlockchainsStack/index.tsx
src/components/GameInfoV2/GameInfoV2.stories.tsx
src/components/GameInfoV2/index.tsx
src/components/MetaSection/MetaSection.stories.tsx
src/components/SocialLinks/SocialLinks.tsx

I figured it might be easier to open a PR showing some changes @biliesilva 
This pull request includes several changes to the `BlockchainsStack` and `GameInfoV2` components, as well as updates to the `SocialLinks` component and storybook files. The main goal is to improve component flexibility and code readability.
* Added an `Image` prop to allow the use of a custom image component instead of the default `img` tag.
* Updated the component to use the `Image` prop in place of the `img` tag for blockchain icons. [[1]](diffhunk://#diff-fa2aa420e4e29863c1f4e2f6c4e22ec96c63ab64b4250b8529750c6fc1814b6bL69-R73) [[2]](diffhunk://#diff-fa2aa420e4e29863c1f4e2f6c4e22ec96c63ab64b4250b8529750c6fc1814b6bL104-R108)
* Replaced the `blockchains` prop with a `ReactNode` to allow for more flexible rendering …

[Tech] refactor game info

---

package.json
src/components/Button/Button.module.scss

Hover effect does not work on client due to `z-index: -1` for the after

[Fix] secondary gradient button after for client

---

package.json
src/components/QuestsSummaryTable/QuestsSummaryTable.stories.tsx
src/components/SearchBar/SearchBar.stories.tsx
src/components/SearchBar/index.tsx

related to https://github.com/HyperPlay-Gaming/hyperplay-pm/issues/591
fixes this error on store
```
intercept-console-error.ts:40 You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`
```
by removing value and just handling the `onInput` calls with a debounce for performance.

[Fix] Search bar value errors

---

package.json
src/components/MarkdownDescription/MarkdownDescription.stories.tsx
src/components/QuestDetails/QuestDetails.stories.tsx
src/components/QuestDetails/index.module.scss

[Fix] Markdown description spacing

---

.github/workflows/publish-ui.yml
package.json

pnpm publish ignores the dist/node_modules, breaking the shipped package. let's use npm publish which is working fine with some local tests

[Tech] Use npm instead of pnpm for publish

---

package.json

only to bump a version that was conflicting with another

chore: bump version to 1.33.2

---

package.json
src/components/CardGeneric/index.tsx
src/components/QuestCard/QuestCard.stories.tsx
src/components/QuestCard/index.tsx

TS was throwing errors when passing `component = "a"` even though it worked. This uses Mantine's `createPolymorphicComponent` to make sure we have the right polymorphic types for these components that ultimately wrap the polymorphic `Card` component from Mantine.

[Tech] Fix quest card props type
